LEARNING_RATES = [1e-2,1e-3,1e-4,1e-5]
#NB_EPOCHS = 200
BATCH_SIZES = [32,63,128]
ACTIVATION_FUNCTIONS = ['relu','leaky_relu','prelu']

IMG_PATCH_SIZE = 80
THRESHOLD_ROAD = 64

DATA_AUGMENTATION = True
POSTPROCESSING = True
MAJORITY_VOTING = True

SEED = 7
CROSS_VALIDATION = True
K_FOLD = 5

CUDA = True

OUTPUT_RAW_PREDICTION = False