LEARNING_RATES = [1e-3]
BATCH_SIZES = [64]
ACTIVATION_FUNCTIONS = ['leaky_relu']
OPTIMIZERS = ['Adam']

IMG_PATCH_SIZE = 80
THRESHOLD_ROAD = 64

DATA_AUGMENTATION = False
POSTPROCESSING = False
MAJORITY_VOTING = True

SEED = 7
RATIO = 0.2

CUDA = True

OUTPUT_RAW_PREDICTION = False